# Generated by Django 3.2.10 on 2022-01-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totoapp', '0003_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
